name: CI/CD Pipeline - Local

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
    
    - name: Test with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: cicdtest-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: false
        tags: cicdtest-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Load Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: cicdtest-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Load Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        load: true
        tags: cicdtest-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run Backend Container
      run: |
        docker run -d --name backend -p 8080:8080 cicdtest-backend:latest
        echo "Backend container started on port 8080"
    
    - name: Run Frontend Container
      run: |
        docker run -d --name frontend -p 3000:3000 cicdtest-frontend:latest
        echo "Frontend container started on port 3000"
    
    - name: Check container status
      run: |
        docker ps
        echo "Containers are running!"
        echo "Backend: http://localhost:8080"
        echo "Frontend: http://localhost:3000"
        echo "Note: These containers are running on GitHub Actions runners and are not accessible from your local machine." 